// lib/hospitals.ts
// MCT Partner Hospitals — data source for /hospitals-in-turkey and /[hospital] pages
// Slugs match the existing WordPress URLs 1:1 — DO NOT change slugs (SEO).
// TODO fields: fill from old site content, rewritten in clean English.

export interface HospitalGroup {
  name: string;
  logo: string;
  description: string;
}

export interface Hospital {
  slug: string;
  name: string;
  group: keyof typeof hospitalGroups;
  city: string;
  district: string;
  accreditations: string[];
  beds: number | null;
  operatingRooms: number | null;
  area: string;
  overview: string;
  languages: string[];
  freeServices: string[];
  treatmentUnits: string[];
  mapEmbedUrl: string;
  images: string[];
}

export const hospitalGroups = {
  acibadem: {
    name: "Acıbadem Healthcare Group",
    logo: "/images/hospitals/groups/acibadem.png",
    description:
      "Founded in 1991, Acıbadem Healthcare Group operates 21 hospitals and 16 outpatient clinics with more than 3,500 doctors and 4,000 nurses, delivering JCI-accredited care across Turkey.", // TODO: refine
  },
  memorial: {
    name: "Memorial Healthcare Group",
    logo: "/images/hospitals/groups/memorial.png",
    description: "", // TODO
  },
  medipol: {
    name: "Medipol Health Group",
    logo: "/images/hospitals/groups/medipol.png",
    description: "", // TODO
  },
  "koc-healthcare": {
    name: "Koç Healthcare Institutions",
    logo: "/images/hospitals/groups/koc-healthcare.png",
    description:
      "American Hospital and Koç University Hospital operate under Koç Healthcare Institutions, the non-profit, research-driven healthcare arm of the Vehbi Koç Foundation.", // TODO: refine
  },
  estethica: {
    name: "Estethica",
    logo: "/images/hospitals/groups/estethica.png",
    description: "", // TODO
  },
} as const;

// Shared defaults — override per hospital where needed
const DEFAULT_FREE_SERVICES = [
  "Free consultation and treatment plan",
  "Airport pickup and VIP transfers",
  "Translation and interpreter services",
  "Hotel booking assistance",
  "Personal patient coordinator",
]; // TODO: confirm against MCT package definitions

export const hospitals: Hospital[] = [
  // ─────────────────────────────── ACIBADEM (15) ───────────────────────────────
  {
    slug: "acibadem-adana-hospital",
    name: "Acıbadem Adana Hospital",
    group: "acibadem",
    city: "Adana",
    district: "",
    accreditations: ["JCI"],
    beds: null, // TODO
    operatingRooms: null, // TODO
    area: "", // TODO
    overview: "", // TODO: rewrite from old page in clean English
    languages: [], // TODO
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [], // TODO
    mapEmbedUrl: "", // TODO
    images: ["/images/hospitals/acibadem-adana/1.jpg"], // TODO
  },
  {
    slug: "acibadem-ankara-hospital",
    name: "Acıbadem Ankara Hospital",
    group: "acibadem",
    city: "Ankara",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-ankara/1.jpg"],
  },
  {
    slug: "acibadem-atasehir-hospital",
    name: "Acıbadem Ataşehir Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Ataşehir",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-atasehir/1.jpg"],
  },
  {
    slug: "acibadem-bakirkoy-hospital",
    name: "Acıbadem Bakırköy Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Bakırköy",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-bakirkoy/1.jpg"],
  },
  {
    slug: "acibadem-bodrum-hospital",
    name: "Acıbadem Bodrum Hospital",
    group: "acibadem",
    city: "Muğla",
    district: "Bodrum",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-bodrum/1.jpg"],
  },
  {
    slug: "acibadem-bursa-hospital",
    name: "Acıbadem Bursa Hospital",
    group: "acibadem",
    city: "Bursa",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-bursa/1.jpg"],
  },
  {
    slug: "acibadem-eskisehir-hospital",
    name: "Acıbadem Eskişehir Hospital",
    group: "acibadem",
    city: "Eskişehir",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-eskisehir/1.jpg"],
  },
  {
    slug: "acibadem-fulya-hospital",
    name: "Acıbadem Fulya Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Fulya",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-fulya/1.jpg"],
  },
  {
    slug: "acibadem-international-hospital",
    name: "Acıbadem International Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Yeşilköy",
    accreditations: ["JCI"],
    beds: 112,
    operatingRooms: null,
    area: "19,000 sqm",
    overview: "", // TODO: old page has content — rewrite (avoid the spun-English text)
    languages: [
      "Arabic",
      "English",
      "French",
      "German",
      "Greek",
      "Romanian",
      "Russian",
      "Swedish",
      "Turkish",
    ],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-international/1.jpg"],
  },
  {
    slug: "acibadem-kadikoy-hospital",
    name: "Acıbadem Kadıköy Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Kadıköy",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kadikoy/1.jpg"],
  },
  {
    slug: "acibadem-kayseri-hospital",
    name: "Acıbadem Kayseri Hospital",
    group: "acibadem",
    city: "Kayseri",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kayseri/1.jpg"],
  },
  {
    slug: "acibadem-kocaeli-hospital",
    name: "Acıbadem Kocaeli Hospital",
    group: "acibadem",
    city: "Kocaeli",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kocaeli/1.jpg"],
  },
  {
    slug: "acibadem-kozyatagi-hospital",
    name: "Acıbadem Kozyatağı Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Kozyatağı",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kozyatagi/1.jpg"],
  },
  {
    slug: "acibadem-maslak-hospital",
    name: "Acıbadem Maslak Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Maslak",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-maslak/1.jpg"],
  },
  {
    slug: "acibadem-taksim-hospital",
    name: "Acıbadem Taksim Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Taksim",
    accreditations: ["JCI"],
    beds: 99,
    operatingRooms: 6,
    area: "24,000 sqm",
    overview: "", // TODO
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-taksim/1.jpg"],
  },

  // ─────────────────────────────── MEMORIAL (8) ───────────────────────────────
  {
    slug: "memorial-ankara-hospital",
    name: "Memorial Ankara Hospital",
    group: "memorial",
    city: "Ankara",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-ankara/1.jpg"],
  },
  {
    slug: "memorial-antalya-hospital",
    name: "Memorial Antalya Hospital",
    group: "memorial",
    city: "Antalya",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-antalya/1.jpg"],
  },
  {
    slug: "memorial-atasehir-hospital",
    name: "Memorial Ataşehir Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Ataşehir",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-atasehir/1.jpg"],
  },
  {
    slug: "memorial-bahcelievler-hospital",
    name: "Memorial Bahçelievler Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Bahçelievler",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-bahcelievler/1.jpg"],
  },
  {
    slug: "memorial-dicle-hospital",
    name: "Memorial Dicle Hospital",
    group: "memorial",
    city: "Diyarbakır",
    district: "",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-dicle/1.jpg"],
  },
  {
    slug: "memorial-diyarbakir-hospital",
    name: "Memorial Diyarbakır Hospital",
    group: "memorial",
    city: "Diyarbakır",
    district: "",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-diyarbakir/1.jpg"],
  },
  {
    slug: "memorial-kayseri-hospital",
    name: "Memorial Kayseri Hospital",
    group: "memorial",
    city: "Kayseri",
    district: "",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-kayseri/1.jpg"],
  },
  {
    slug: "memorial-sisli-hospital",
    name: "Memorial Şişli Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Şişli",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/memorial-sisli/1.jpg"],
  },

  // ─────────────────────────────── MEDIPOL (10) ───────────────────────────────
  {
    slug: "medipol-ankara-university-hospital",
    name: "Medipol Ankara University Hospital",
    group: "medipol",
    city: "Ankara",
    district: "",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-ankara/1.jpg"],
  },
  {
    slug: "medipol-bahcelievler-hospital",
    name: "Medipol Bahçelievler Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Bahçelievler",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-bahcelievler/1.jpg"],
  },
  {
    slug: "medipol-camlica-university-hospital",
    name: "Medipol Çamlıca University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Çamlıca",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-camlica/1.jpg"],
  },
  {
    slug: "medipol-esenler-university-hospital",
    name: "Medipol Esenler University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Esenler",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-esenler/1.jpg"],
  },
  {
    slug: "medipol-istanbul-hospital",
    name: "Medipol Istanbul Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "", // TODO: confirm district
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-istanbul/1.jpg"],
  },
  {
    slug: "medipol-mega-university-hospital",
    name: "Medipol Mega University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Bağcılar",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-mega/1.jpg"],
  },
  {
    slug: "medipol-pendik-university-hospital",
    name: "Medipol Pendik University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Pendik",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-pendik/1.jpg"],
  },
  {
    slug: "medipol-sefakoy-university-hospital",
    name: "Medipol Sefaköy University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Sefaköy",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-sefakoy/1.jpg"],
  },
  {
    slug: "medipol-unkapani-university-hospital",
    name: "Medipol Unkapanı University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Unkapanı",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-unkapani/1.jpg"],
  },
  {
    slug: "medipol-vatan-university-hospital",
    name: "Medipol Vatan University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Fatih",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-vatan/1.jpg"],
  },

  // ────────────────────── KOÇ HEALTHCARE INSTITUTIONS (2) ──────────────────────
  {
    slug: "koc-university-hospital",
    name: "Koç University Hospital",
    group: "koc-healthcare",
    city: "Istanbul",
    district: "Topkapı",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/koc-university/1.jpg"],
  },
  {
    slug: "american-hospital",
    name: "American Hospital",
    group: "koc-healthcare",
    city: "Istanbul",
    district: "Nişantaşı",
    accreditations: ["JCI", "ISO 9001", "ISO 14001", "ISO 27001"],
    beds: 241,
    operatingRooms: 12,
    area: "",
    overview: "", // TODO: strong content on old page — 97 years of history, Superbrands award, 130k outpatients/year
    languages: [], // TODO: old page lists 20 languages
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/american/1.jpg"],
  },

  // ─────────────────────────────── ESTETHICA (1) ───────────────────────────────
  {
    slug: "estethica",
    name: "Estethica",
    group: "estethica",
    city: "Istanbul",
    district: "", // TODO: Ataşehir / Levent — confirm which branch to show
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/estethica/1.jpg"],
  },
];

// ─────────────────────────────── HELPERS ───────────────────────────────

export function getHospitalBySlug(slug: string): Hospital | undefined {
  return hospitals.find((h) => h.slug === slug);
}

export function getHospitalsByGroup(groupKey: keyof typeof hospitalGroups): Hospital[] {
  return hospitals.filter((h) => h.group === groupKey);
}

export function getAllHospitalSlugs(): string[] {
  return hospitals.map((h) => h.slug);
}
