// lib/hospitals.ts
// MCT Partner Hospitals — data source for /hospitals-in-turkey and /[hospital] pages
// Slugs match the existing WordPress URLs 1:1 — DO NOT change slugs (SEO).
// TODO fields: fill from old site content, rewritten in clean English.

export interface HospitalGroup {
  name: string;
  logo: string;
  description: string;
}

export interface Hospital {
  slug: string;
  name: string;
  group: keyof typeof hospitalGroups;
  city: string;
  district: string;
  accreditations: string[];
  beds: number | null;
  operatingRooms: number | null;
  area: string;
  overview: string;
  languages: string[];
  freeServices: string[];
  treatmentUnits: string[];
  mapEmbedUrl: string;
  images: string[];
}

export const hospitalGroups = {
  acibadem: {
    name: "Acıbadem Healthcare Group",
    logo: "/images/hospitals/groups/acibadem.png",
    description:
      "Founded in 1991, Acıbadem Healthcare Group operates 21 hospitals and 16 outpatient clinics with more than 3,500 doctors and 4,000 nurses, delivering JCI-accredited care across Turkey.", // TODO: refine
  },
  memorial: {
    name: "Memorial Healthcare Group",
    logo: "/images/hospitals/groups/memorial.png",
    description:
      "Memorial Healthcare Group opened its first hospital, Memorial Şişli, in February 2000 and has since grown into one of Turkey's leading private hospital networks, with more than 1,300 physicians — over 700 holding academic titles — and 7,300+ healthcare professionals. Memorial Şişli was the first hospital in Turkey, and the 21st in the world, to earn JCI (Joint Commission International) accreditation, and the group is internationally recognized in organ transplantation, IVF, oncology, cardiology, and cardiovascular surgery.",
  },
  medipol: {
    name: "Medipol Health Group",
    logo: "/images/hospitals/groups/medipol.png",
    description: "", // TODO
  },
  "koc-healthcare": {
    name: "Koç Healthcare Institutions",
    logo: "/images/hospitals/groups/koc-healthcare.png",
    description:
      "American Hospital and Koç University Hospital operate under Koç Healthcare Institutions, the non-profit, research-driven healthcare arm of the Vehbi Koç Foundation.", // TODO: refine
  },
  estethica: {
    name: "Estethica",
    logo: "/images/hospitals/groups/estethica.png",
    description: "", // TODO
  },
} as const;

// Shared defaults — override per hospital where needed
const DEFAULT_FREE_SERVICES = [
  "Free consultation and treatment plan",
  "Airport pickup and VIP transfers",
  "Translation and interpreter services",
  "Hotel booking assistance",
  "Personal patient coordinator",
]; // TODO: confirm against MCT package definitions

export const MEMORIAL_LANGUAGES = [
  "English",
  "Arabic",
  "French",
  "German",
  "Greek",
  "Romanian",
  "Russian",
  "Swedish",
  "Turkish",
];

export const MEMORIAL_TREATMENT_UNITS = [
  "Allergy & Immunology",
  "Anesthesiology and Reanimation",
  "Audiology",
  "Cardiology",
  "Cardiovascular Surgery",
  "Check-Up",
  "Clinical Laboratories",
  "Dermatology",
  "Ear, Nose and Throat",
  "Emergency Service",
  "Endocrinology",
  "Gastroenterology",
  "General Surgery",
  "Hematology",
  "Infectious Diseases",
  "Intensive Care Units (General, Coronary, Neonatal)",
  "Internal Medicine",
  "IVF",
  "Medical Oncology",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Nutrition and Diet",
  "Obstetrics and Gynaecology",
  "Ophthalmology",
  "Oral and Dental Health",
  "Orthopedics and Traumatology",
  "Pain Management",
  "Pathology",
  "Pediatric Surgery",
  "Pediatrics",
  "Physiotherapy and Rehabilitation",
  "Plastic and Reconstructive Surgery",
  "Psychiatry",
  "Psychology",
  "Pulmonary Medicine",
  "Radiation Oncology",
  "Radiology and Medical Imaging",
  "Rheumatology",
  "Sleep Disorders Lab",
  "Speech and Language Pathology",
  "Thoracic Surgery",
  "Urology",
  "Vascular Surgery",
];

export const hospitals: Hospital[] = [
  // ─────────────────────────────── ACIBADEM (15) ───────────────────────────────
  {
    slug: "acibadem-adana-hospital",
    name: "Acıbadem Adana Hospital",
    group: "acibadem",
    city: "Adana",
    district: "",
    accreditations: ["JCI"],
    beds: null, // TODO
    operatingRooms: null, // TODO
    area: "", // TODO
    overview: "", // TODO: rewrite from old page in clean English
    languages: [], // TODO
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [], // TODO
    mapEmbedUrl: "", // TODO
    images: ["/images/hospitals/acibadem-adana/1.jpg"], // TODO
  },
  {
    slug: "acibadem-ankara-hospital",
    name: "Acıbadem Ankara Hospital",
    group: "acibadem",
    city: "Ankara",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-ankara/1.jpg"],
  },
  {
    slug: "acibadem-atasehir-hospital",
    name: "Acıbadem Ataşehir Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Ataşehir",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-atasehir/1.jpg"],
  },
  {
    slug: "acibadem-bakirkoy-hospital",
    name: "Acıbadem Bakırköy Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Bakırköy",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-bakirkoy/1.jpg"],
  },
  {
    slug: "acibadem-bodrum-hospital",
    name: "Acıbadem Bodrum Hospital",
    group: "acibadem",
    city: "Muğla",
    district: "Bodrum",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-bodrum/1.jpg"],
  },
  {
    slug: "acibadem-bursa-hospital",
    name: "Acıbadem Bursa Hospital",
    group: "acibadem",
    city: "Bursa",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-bursa/1.jpg"],
  },
  {
    slug: "acibadem-eskisehir-hospital",
    name: "Acıbadem Eskişehir Hospital",
    group: "acibadem",
    city: "Eskişehir",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-eskisehir/1.jpg"],
  },
  {
    slug: "acibadem-fulya-hospital",
    name: "Acıbadem Fulya Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Fulya",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-fulya/1.jpg"],
  },
  {
    slug: "acibadem-international-hospital",
    name: "Acıbadem International Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Yeşilköy",
    accreditations: ["JCI"],
    beds: 112,
    operatingRooms: null,
    area: "19,000 sqm",
    overview: "", // TODO: old page has content — rewrite (avoid the spun-English text)
    languages: [
      "Arabic",
      "English",
      "French",
      "German",
      "Greek",
      "Romanian",
      "Russian",
      "Swedish",
      "Turkish",
    ],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-international/1.jpg"],
  },
  {
    slug: "acibadem-kadikoy-hospital",
    name: "Acıbadem Kadıköy Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Kadıköy",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kadikoy/1.jpg"],
  },
  {
    slug: "acibadem-kayseri-hospital",
    name: "Acıbadem Kayseri Hospital",
    group: "acibadem",
    city: "Kayseri",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kayseri/1.jpg"],
  },
  {
    slug: "acibadem-kocaeli-hospital",
    name: "Acıbadem Kocaeli Hospital",
    group: "acibadem",
    city: "Kocaeli",
    district: "",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kocaeli/1.jpg"],
  },
  {
    slug: "acibadem-kozyatagi-hospital",
    name: "Acıbadem Kozyatağı Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Kozyatağı",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-kozyatagi/1.jpg"],
  },
  {
    slug: "acibadem-maslak-hospital",
    name: "Acıbadem Maslak Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Maslak",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-maslak/1.jpg"],
  },
  {
    slug: "acibadem-taksim-hospital",
    name: "Acıbadem Taksim Hospital",
    group: "acibadem",
    city: "Istanbul",
    district: "Taksim",
    accreditations: ["JCI"],
    beds: 99,
    operatingRooms: 6,
    area: "24,000 sqm",
    overview: "", // TODO
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/acibadem-taksim/1.jpg"],
  },

  // ─────────────────────────────── MEMORIAL (9) ───────────────────────────────
  {
    slug: "memorial-sisli-hospital",
    name: "Memorial Şişli Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Şişli",
    accreditations: ["JCI", "ISO"],
    beds: 252,
    operatingRooms: 13,
    area: "53,000 m²",
    overview:
      "Memorial Şişli Hospital is the flagship of Memorial Healthcare Group. Planned from 1996 with the support of ECRI, one of the leading hospital consultancy firms in the United States, it welcomed its first patient in February 2000 on the European side of Istanbul. Just two years later it became the first hospital in Turkey — and the 21st in the world — to receive JCI (Joint Commission International) accreditation, setting a new benchmark for healthcare quality in the country.\n\nOperating on a 53,000 m² closed area, the hospital serves with a 252-bed capacity, 13 operating rooms, four intensive care units (cardiovascular surgery, general, coronary, and neonatal), and three laboratories. Its specialized centers include the Organ Transplantation Center, IVF and Genetics Center, Stroke Center, Breast Health Center, Oncology Center, da Vinci Robotic Surgery Center, and Bone Marrow Transplant Center. Today Memorial Şişli is an international reference hospital receiving patients from 167 countries.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=41.061527,28.972632&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-sisli/1.jpg",
      "/images/hospitals/memorial-sisli/2.jpg",
      "/images/hospitals/memorial-sisli/3.jpg",
      "/images/hospitals/memorial-sisli/4.jpg",
    ],
  },
  {
    slug: "memorial-atasehir-hospital",
    name: "Memorial Ataşehir Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Ataşehir",
    accreditations: [],
    beds: 144,
    operatingRooms: null,
    area: "22,000 m²",
    overview:
      "Memorial Ataşehir Hospital, opened in 2010, brings Memorial Healthcare Group's international standards to the Anatolian side of Istanbul. The hospital was designed down to the smallest detail — modern architecture, advanced medical technology, and comfortable patient rooms — so that patients feel both special and safe, and it operates around the clock in every specialty.\n\nSet on a 22,000 m² campus with a 144-bed capacity, the hospital is particularly strong in cardiovascular surgery, organ transplantation, medical oncology, da Vinci robotic surgery, and IVF, serving as Memorial's IVF treatment base on the Anatolian side. Its Organ Transplant Center performs liver and kidney transplants with success rates above the world average, and the facility includes Coronary, General, Cardiovascular Surgery, and Neonatal intensive care units, a coronary angiography service, and MR and CT rooms designed with ambient technology to keep patients relaxed during imaging.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=40.984375,29.106864&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-atasehir/1.jpg",
      "/images/hospitals/memorial-atasehir/2.jpg",
      "/images/hospitals/memorial-atasehir/3.jpg",
      "/images/hospitals/memorial-atasehir/4.jpg",
    ],
  },
  {
    slug: "memorial-bahcelievler-hospital",
    name: "Memorial Bahçelievler Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Bahçelievler",
    accreditations: ["JCI", "LEED Platinum"],
    beds: 320,
    operatingRooms: 15,
    area: "72,000 m²",
    overview:
      "Memorial Bahçelievler Hospital, the 11th hospital of Memorial Healthcare Group, opened in February 2018 as one of the most comprehensive health complexes in the world. It holds the prestigious LEED Platinum certificate for energy-efficient, environmentally friendly design — awarded only to leading green buildings worldwide — and was designed as one of the finest examples of contemporary hospital architecture, where the healing influence of nature and art is built into the patient experience.\n\nServing on a 72,000 m² campus that includes 8,000 m² of green space, the hospital offers a 320-bed capacity, 15 operating theaters — one of them a hybrid operating room — 49 intensive care beds, 31 medical observation rooms, and 135 outpatient clinics. Its technology includes the Elekta Versa HD Signature radiotherapy system for cancer treatment, da Vinci robotic surgery, 3 Tesla MRI, dual-energy CT, and PET-CT, and its intensive care units were the first in Turkey to feature fixed patient-lift systems in every room.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=40.993097,28.852337&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-bahcelievler/1.jpg",
      "/images/hospitals/memorial-bahcelievler/2.jpg",
      "/images/hospitals/memorial-bahcelievler/3.jpg",
      "/images/hospitals/memorial-bahcelievler/4.jpg",
    ],
  },
  {
    slug: "memorial-goztepe-hospital",
    name: "Memorial Göztepe Hospital",
    group: "memorial",
    city: "Istanbul",
    district: "Göztepe",
    accreditations: [],
    beds: 300,
    operatingRooms: 19,
    area: "81,000 m²",
    overview:
      "Memorial Göztepe Hospital is the newest member of Memorial Healthcare Group, opened in November 2025 as the group's 13th hospital and one of the largest health investments on the Anatolian side of Istanbul. Built from the ground up as an eco-friendly, energy-efficient project that integrates art and architecture into the healing environment, it was designed to set a new standard of care for Istanbul and the wider region, with excellent transport access close to Sabiha Gökçen Airport and the metro network.\n\nSpanning an 81,000 m² closed area, the hospital offers a capacity of more than 300 beds, 19 operating theaters including hybrid operating rooms, 55 intensive care beds, and 127 outpatient clinics. Its hybrid operating rooms are equipped with advanced imaging systems that allow surgeons to perform complex cardiac, neurosurgical, orthopedic, and endovascular procedures with maximum precision, while robotic rehabilitation systems accelerate recovery for neurological and orthopedic patients. Specialized strengths include a multidisciplinary Heart Team, a comprehensive stroke unit with 24/7 interventional neuroradiology, one of Turkey's largest private bone marrow transplant centers, organ transplantation, oncology, a one-stop Check-Up Center, and a dedicated child-friendly pediatric ecosystem with its own play areas and consultation rooms.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl:
      "https://maps.google.com/maps?q=Memorial+G%C3%B6ztepe+Hastanesi+Istanbul&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-goztepe/1.jpg",
      "/images/hospitals/memorial-goztepe/2.jpg",
      "/images/hospitals/memorial-goztepe/3.jpg",
      "/images/hospitals/memorial-goztepe/4.jpg",
    ],
  },
  {
    slug: "memorial-ankara-hospital",
    name: "Memorial Ankara Hospital",
    group: "memorial",
    city: "Ankara",
    district: "Çankaya",
    accreditations: ["JCI"],
    beds: 230,
    operatingRooms: 11,
    area: "42,000 m²",
    overview:
      "Memorial Ankara Hospital, the 10th hospital of Memorial Healthcare Group, brings the group's world-class standards to Turkey's capital. One of the largest private hospitals in Ankara with a 42,000 m² closed area, it serves as a regional healthcare hub for Central Anatolia, the Black Sea region, and international patients, with reference-level departments, an academic medical faculty, and easy access on the Konya highway.\n\nThe hospital offers a 230-bed capacity — 60 of which are in intensive care — 11 fully equipped operating rooms, and 63 outpatient clinics. It hosts Memorial's globally recognized departments including cardiovascular surgery, invasive cardiology, medical and radiation oncology, bone marrow transplantation, IVF, orthopedics, and neurosurgery. Technology is built around patient comfort: a 256-slice CT scanner minimizes radiation exposure, a wide-bore 70 cm MRI eases claustrophobia, and operating rooms use adjustable LED lighting that meets international surgical standards.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=39.903538,32.815306&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-ankara/1.jpg",
      "/images/hospitals/memorial-ankara/2.jpg",
      "/images/hospitals/memorial-ankara/3.jpg",
      "/images/hospitals/memorial-ankara/4.jpg",
    ],
  },
  {
    slug: "memorial-antalya-hospital",
    name: "Memorial Antalya Hospital",
    group: "memorial",
    city: "Antalya",
    district: "Kepez",
    accreditations: ["JCI"],
    beds: 114,
    operatingRooms: 5,
    area: "15,000 m²",
    overview:
      "Memorial Antalya Hospital represents Memorial Healthcare Group on Turkey's Mediterranean coast and is one of the region's most important contributors to health tourism, welcoming patients from 167 countries. Shortly after opening, the hospital received JCI (Joint Commission International) accreditation and has renewed it in successive three-year cycles. Its central Kepez location keeps it close to Antalya's holiday resorts, the airport, and the main bus terminal.\n\nThe hospital serves with 114 patient beds and 28 intensive care beds, five operating theaters, an advanced radiology department, an interventional radiology unit, a coronary angiography service, and a chemotherapy unit. Modern architectural design and patient rooms with five-star hotel comfort support recovery, and intensive care units feature day-night ambient lighting designed to positively affect patient psychology. As a paperless, filmless hospital, it shares imaging and laboratory results digitally with all Memorial hospitals across Turkey.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=36.917617,30.69347&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-antalya/1.jpg",
      "/images/hospitals/memorial-antalya/2.jpg",
      "/images/hospitals/memorial-antalya/3.jpg",
      "/images/hospitals/memorial-antalya/4.jpg",
    ],
  },
  {
    slug: "memorial-kayseri-hospital",
    name: "Memorial Kayseri Hospital",
    group: "memorial",
    city: "Kayseri",
    district: "Kocasinan",
    accreditations: [],
    beds: 119,
    operatingRooms: 5,
    area: "11,000 m²",
    overview:
      "Memorial Kayseri Hospital opened in 2013 as the 9th hospital of Memorial Healthcare Group, carrying the group's excellence-focused service culture to the Central Anatolia region. With a respected academic physician staff and modern patient rooms and living areas, it is positioned to meet the full range of healthcare needs of the region at international standards.\n\nSet on an 11,000 m² area, the hospital offers a 119-bed capacity and five technologically advanced operating rooms, with state-of-the-art imaging units, laboratories, and intensive care units. Through the PACS filmless hospital system it shares imaging and laboratory results with all Memorial hospitals across Turkey. The hospital also hosts the Memorial Kayseri IVF Center — the only architecturally independent IVF center in Central Anatolia — with a 10-bed capacity, advanced embryology, andrology, and embryo-freezing laboratories, serving both regional and international patients.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=38.728712,35.479552&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-kayseri/1.jpg",
      "/images/hospitals/memorial-kayseri/2.jpg",
      "/images/hospitals/memorial-kayseri/3.jpg",
      "/images/hospitals/memorial-kayseri/4.jpg",
    ],
  },
  {
    slug: "memorial-diyarbakir-hospital",
    name: "Memorial Diyarbakır Hospital",
    group: "memorial",
    city: "Diyarbakır",
    district: "Kayapınar",
    accreditations: [],
    beds: 141,
    operatingRooms: 6,
    area: "14,000 m²",
    overview:
      "Memorial Diyarbakır Hospital opened in 2011 as the 7th hospital of Memorial Healthcare Group, bringing the group's international standards to Southeastern Anatolia. One of Memorial's two hospitals in the city, it is designed to serve not only Diyarbakır but the entire region and international patients, with an academic staff of specialist physicians, modern diagnostic and treatment units, and architecture built around patient comfort.\n\nFounded on a 14,000 m² covered area, the hospital offers a 141-bed capacity, six operating rooms, and 43 intensive care beds (23 neonatal, 20 general). Its Oncology Center is the regional reference for cancer care, combining medical oncology, radiation oncology (Varian IMRT LINAC), nuclear medicine (PET-CT and scintigraphy), interventional radiology, and oncological surgery under one roof to create a personalized treatment plan for every patient. Comfortable suite rooms and sections designed for patients with disabilities complete the facility.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=37.936,40.187779&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-diyarbakir/1.jpg",
      "/images/hospitals/memorial-diyarbakir/2.jpg",
      "/images/hospitals/memorial-diyarbakir/3.jpg",
      "/images/hospitals/memorial-diyarbakir/4.jpg",
    ],
  },
  {
    slug: "memorial-dicle-hospital",
    name: "Memorial Dicle Hospital",
    group: "memorial",
    city: "Diyarbakır",
    district: "Kayapınar",
    accreditations: [],
    beds: 135,
    operatingRooms: 9,
    area: "21,000 m²",
    overview:
      "Memorial Dicle Hospital opened in 2013 as the 8th hospital of Memorial Healthcare Group and its second in Diyarbakır. Located on the Şanlıurfa road close to the airport, hotel chains, and the bus terminal, it is strategically positioned to serve the entire Southeastern Anatolia region as well as international patients, with an academic staff of specialist physicians and architecture designed for patient comfort.\n\nEstablished on a 21,000 m² closed area, the hospital offers a 135-bed capacity, nine operating rooms, and 78 intensive care beds in total — 50 neonatal, 16 general, 5 cardiology, and 7 cardiovascular surgery. It serves as the region's reference center in cardiology, interventional cardiology, and cardiovascular surgery, performing complex procedures such as CTO interventions, EPS ablation, TAVI, coronary bypass, and heart valve repair and replacement. The facility also includes an IVF center with genetic testing, the region's most comprehensive pediatric orthopedics department, comfortable suite rooms, and sections designed for patients with disabilities.",
    languages: MEMORIAL_LANGUAGES,
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: MEMORIAL_TREATMENT_UNITS,
    mapEmbedUrl: "https://maps.google.com/maps?q=37.925497,40.162134&z=14&output=embed",
    images: [
      "/images/hospitals/memorial-dicle/1.jpg",
      "/images/hospitals/memorial-dicle/2.jpg",
      "/images/hospitals/memorial-dicle/3.jpg",
      "/images/hospitals/memorial-dicle/4.jpg",
    ],
  },

  // ─────────────────────────────── MEDIPOL (10) ───────────────────────────────
  {
    slug: "medipol-ankara-university-hospital",
    name: "Medipol Ankara University Hospital",
    group: "medipol",
    city: "Ankara",
    district: "",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-ankara/1.jpg"],
  },
  {
    slug: "medipol-bahcelievler-hospital",
    name: "Medipol Bahçelievler Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Bahçelievler",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-bahcelievler/1.jpg"],
  },
  {
    slug: "medipol-camlica-university-hospital",
    name: "Medipol Çamlıca University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Çamlıca",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-camlica/1.jpg"],
  },
  {
    slug: "medipol-esenler-university-hospital",
    name: "Medipol Esenler University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Esenler",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-esenler/1.jpg"],
  },
  {
    slug: "medipol-istanbul-hospital",
    name: "Medipol Istanbul Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "", // TODO: confirm district
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-istanbul/1.jpg"],
  },
  {
    slug: "medipol-mega-university-hospital",
    name: "Medipol Mega University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Bağcılar",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-mega/1.jpg"],
  },
  {
    slug: "medipol-pendik-university-hospital",
    name: "Medipol Pendik University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Pendik",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-pendik/1.jpg"],
  },
  {
    slug: "medipol-sefakoy-university-hospital",
    name: "Medipol Sefaköy University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Sefaköy",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-sefakoy/1.jpg"],
  },
  {
    slug: "medipol-unkapani-university-hospital",
    name: "Medipol Unkapanı University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Unkapanı",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-unkapani/1.jpg"],
  },
  {
    slug: "medipol-vatan-university-hospital",
    name: "Medipol Vatan University Hospital",
    group: "medipol",
    city: "Istanbul",
    district: "Fatih",
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/medipol-vatan/1.jpg"],
  },

  // ────────────────────── KOÇ HEALTHCARE INSTITUTIONS (2) ──────────────────────
  {
    slug: "koc-university-hospital",
    name: "Koç University Hospital",
    group: "koc-healthcare",
    city: "Istanbul",
    district: "Topkapı",
    accreditations: ["JCI"],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/koc-university/1.jpg"],
  },
  {
    slug: "american-hospital",
    name: "American Hospital",
    group: "koc-healthcare",
    city: "Istanbul",
    district: "Nişantaşı",
    accreditations: ["JCI", "ISO 9001", "ISO 14001", "ISO 27001"],
    beds: 241,
    operatingRooms: 12,
    area: "",
    overview: "", // TODO: strong content on old page — 97 years of history, Superbrands award, 130k outpatients/year
    languages: [], // TODO: old page lists 20 languages
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/american/1.jpg"],
  },

  // ─────────────────────────────── ESTETHICA (1) ───────────────────────────────
  {
    slug: "estethica",
    name: "Estethica",
    group: "estethica",
    city: "Istanbul",
    district: "", // TODO: Ataşehir / Levent — confirm which branch to show
    accreditations: [],
    beds: null,
    operatingRooms: null,
    area: "",
    overview: "",
    languages: [],
    freeServices: DEFAULT_FREE_SERVICES,
    treatmentUnits: [],
    mapEmbedUrl: "",
    images: ["/images/hospitals/estethica/1.jpg"],
  },
];

// ─────────────────────────────── HELPERS ───────────────────────────────

export function getHospitalBySlug(slug: string): Hospital | undefined {
  return hospitals.find((h) => h.slug === slug);
}

export function getHospitalsByGroup(groupKey: keyof typeof hospitalGroups): Hospital[] {
  return hospitals.filter((h) => h.group === groupKey);
}

export function getAllHospitalSlugs(): string[] {
  return hospitals.map((h) => h.slug);
}
